'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Cpu', [
      {
        cpuId: 1,
        partId: 1,
        series: 'Intel Core Ultra 9',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 24,
        threadCount: 24,
        performanceCoreClock: 3.7,
        performanceCoreBoostClock: 5.7,
        efficiencyCoreClock: 3.2,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 40,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 2,
        partId: 2,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: 3.9,
        performanceCoreBoostClock: 5.5,
        efficiencyCoreClock: 3.3,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 36,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 3,
        partId: 3,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: 4.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 3.6,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 26,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 159,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 4,
        partId: 4,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: 3.9,
        performanceCoreBoostClock: 5.5,
        efficiencyCoreClock: 3.3,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 36,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'None',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 5,
        partId: 5,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: 4.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 3.6,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 26,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 159,
        integrated: 'None',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 6,
        partId: 6,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 16,
        threadCount: 32,
        performanceCoreClock: 4.3,
        performanceCoreBoostClock: 5.7,
        lTwoCache: 16,
        lThreeCache: 64,
        tdp: 170,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 7,
        partId: 7,
        series: 'AMD Ryzen 7',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 8,
        threadCount: 16,
        performanceCoreClock: 3.8,
        performanceCoreBoostClock: 5.5,
        lTwoCache: 8,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 8,
        partId: 8,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 12,
        threadCount: 24,
        performanceCoreClock: 4.4,
        performanceCoreBoostClock: 5.6,
        lTwoCache: 12,
        lThreeCache: 64,
        tdp: 120,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 9,
        partId: 9,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 3.0,
        performanceCoreBoostClock: 5.4,
        lTwoCache: 6,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 10,
        partId: 10,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 3',
        coreFamily: 'Vermeer',
        socket: 'AM4',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 3.7,
        performanceCoreBoostClock: 4.6,
        lTwoCache: 3,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 11,
        partId: 11,
        series: 'Intel Core i9',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 24,
        threadCount: 32,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 6.0,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 4.4,
        lTwoCache: 36,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cpu', null, {}); // Delete all Cpu records
  }
};

