'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Cpu', [
      {
        cpuId: 1,
        partId: 1,
        series: 'Intel Core Ultra 9',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 24,
        threadCount: 24,
        performanceCoreClock: '3.7 GHz',
        performanceCoreBoostClock: '5.7 GHz',
        efficiencyCoreClock: '3.2 GHz',
        efficiencyCoreBoostClock: '4.6 GHz',
        lTwoCache: '40 MB',
        lThreeCache: '36 MB',
        tdp: '125 W',
        maxTurboPower: '250 W',
        integrated: 'Intel Xe',
        memoryMax: '192 GB',
        lithography: '3 nm',
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 2,
        partId: 2,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: '3.9 GHz',
        performanceCoreBoostClock: '5.5 GHz',
        efficiencyCoreClock: '3.3 GHz',
        efficiencyCoreBoostClock: '4.6 GHz',
        lTwoCache: '36 MB',
        lThreeCache: '30 MB',
        tdp: '125 W',
        maxTurboPower: '250 W',
        integrated: 'Intel Xe',
        memoryMax: '192 GB',
        lithography: '3 nm',
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 3,
        partId: 3,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: '4.2 GHz',
        performanceCoreBoostClock: '5.2 GHz',
        efficiencyCoreClock: '3.6 GHz',
        efficiencyCoreBoostClock: '4.6 GHz',
        lTwoCache: '26 MB',
        lThreeCache: '24 MB',
        tdp: '125 W',
        maxTurboPower: '159 W',
        integrated: 'Intel Xe',
        memoryMax: '192 GB',
        lithography: '3 nm',
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 4,
        partId: 4,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: '3.9 GHz',
        performanceCoreBoostClock: '5.5 GHz',
        efficiencyCoreClock: '3.3 GHz',
        efficiencyCoreBoostClock: '4.6 GHz',
        lTwoCache: '36 MB',
        lThreeCache: '30 MB',
        tdp: '125 W',
        maxTurboPower: '250 W',
        integrated: 'None',
        memoryMax: '192 GB',
        lithography: '3 nm',
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 5,
        partId: 5,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: '4.2 GHz',
        performanceCoreBoostClock: '5.2 GHz',
        efficiencyCoreClock: '3.6 GHz',
        efficiencyCoreBoostClock: '4.6 GHz',
        lTwoCache: '26 MB',
        lThreeCache: '24 MB',
        tdp: '125 W',
        maxTurboPower: '159 W',
        integrated: 'None',
        memoryMax: '192 GB',
        lithography: '3 nm',
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 6,
        partId: 6,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 16,
        threadCount: 32,
        performanceCoreClock: '4.3 GHz',
        performanceCoreBoostClock: '5.7 GHz',
        lTwoCache: '16 MB',
        lThreeCache: '64 MB',
        tdp: '170 W',
        integrated: 'Radeon',
        memoryMax: '192 GB',
        lithography: '4 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 7,
        partId: 7,
        series: 'AMD Ryzen 7',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 8,
        threadCount: 16,
        performanceCoreClock: '3.8 GHz',
        performanceCoreBoostClock: '5.5 GHz',
        lTwoCache: '8 MB',
        lThreeCache: '32 MB',
        tdp: '65 W',
        integrated: 'Radeon',
        memoryMax: '192 GB',
        lithography: '4 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 8,
        partId: 8,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 12,
        threadCount: 24,
        performanceCoreClock: '4.4 GHz',
        performanceCoreBoostClock: '5.6 GHz',
        lTwoCache: '12 MB',
        lThreeCache: '64 MB',
        tdp: '120 W',
        integrated: 'Radeon',
        memoryMax: '192 GB',
        lithography: '4 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 9,
        partId: 9,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: '3.0 GHz',
        performanceCoreBoostClock: '5.4 GHz',
        lTwoCache: '6 MB',
        lThreeCache: '32 MB',
        tdp: '65 W',
        integrated: 'Radeon',
        memoryMax: '192 GB',
        lithography: '4 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 10,
        partId: 10,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 3',
        coreFamily: 'Vermeer',
        socket: 'AM4',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: '3.7 GHz',
        performanceCoreBoostClock: '4.6 GHz',
        lTwoCache: '3 MB',
        lThreeCache: '32 MB',
        tdp: '65 W',
        integrated: 'None',
        memoryMax: '192 GB',
        lithography: '7 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 11,
        partId: 11,
        series: 'Intel Core i9',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 24,
        threadCount: 32,
        performanceCoreClock: '3.2 GHz',
        performanceCoreBoostClock: '6.0 GHz',
        efficiencyCoreClock: '2.4 GHz',
        efficiencyCoreBoostClock: '4.4 GHz',
        lTwoCache: '36 MB',
        lThreeCache: '36 MB',
        tdp: '125 W',
        maxTurboPower: '253 W',
        integrated: 'Intel UHD Graphics 770',
        memoryMax: '192 GB',
        lithography: '7 nm',
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cpu', null, {}); // Delete all Cpu records
  }
};

