'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Cpu', [
      {
        cpuId: 1,
        partId: 1,
        series: 'Intel Core Ultra 9',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 24,
        threadCount: 24,
        performanceCoreClock: 3.7,
        performanceCoreBoostClock: 5.7,
        efficiencyCoreClock: 3.2,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 40,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 2,
        partId: 2,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: 3.9,
        performanceCoreBoostClock: 5.5,
        efficiencyCoreClock: 3.3,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 36,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 3,
        partId: 3,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: 4.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 3.6,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 26,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 159,
        integrated: 'Intel Xe',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 4,
        partId: 4,
        series: 'Intel Core Ultra 7',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 20,
        threadCount: 20,
        performanceCoreClock: 3.9,
        performanceCoreBoostClock: 5.5,
        efficiencyCoreClock: 3.3,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 36,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 250,
        integrated: 'None',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 5,
        partId: 5,
        series: 'Intel Core Ultra 5',
        microarchitecture: 'Arrow Lake',
        coreFamily: 'Arrow Lake',
        socket: 'LGA1851',
        coreCount: 14,
        threadCount: 14,
        performanceCoreClock: 4.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 3.6,
        efficiencyCoreBoostClock: 4.6,
        lTwoCache: 26,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 159,
        integrated: 'None',
        memoryMax: 192,
        lithography: 3,
        includedCooler: 0,
        multithreading: 0, // tinyint(0) for false
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 6,
        partId: 6,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 16,
        threadCount: 32,
        performanceCoreClock: 4.3,
        performanceCoreBoostClock: 5.7,
        lTwoCache: 16,
        lThreeCache: 64,
        tdp: 170,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 7,
        partId: 7,
        series: 'AMD Ryzen 7',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 8,
        threadCount: 16,
        performanceCoreClock: 3.8,
        performanceCoreBoostClock: 5.5,
        lTwoCache: 8,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 8,
        partId: 8,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 12,
        threadCount: 24,
        performanceCoreClock: 4.4,
        performanceCoreBoostClock: 5.6,
        lTwoCache: 12,
        lThreeCache: 64,
        tdp: 120,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 9,
        partId: 9,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 5',
        coreFamily: 'Granite Ridge',
        socket: 'AM5',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 3.0,
        performanceCoreBoostClock: 5.4,
        lTwoCache: 6,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'Radeon',
        memoryMax: 192,
        lithography: 4,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 10,
        partId: 10,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 3',
        coreFamily: 'Vermeer',
        socket: 'AM4',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 3.7,
        performanceCoreBoostClock: 4.6,
        lTwoCache: 3,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 11,
        partId: 11,
        series: 'Intel Core i9',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 24,
        threadCount: 32,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 6.0,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 4.4,
        lTwoCache: 32,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 12,
        partId: 31,
        series: 'Intel Core i9',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 24,
        threadCount: 32,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 6.0,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 4.4,
        lTwoCache: 32,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 13,
        partId: 32,
        series: 'Intel Core i7',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 20,
        threadCount: 28,
        performanceCoreClock: 3.4,
        performanceCoreBoostClock: 5.6,
        efficiencyCoreClock: 2.5,
        efficiencyCoreBoostClock: 4.3,
        lTwoCache: 28,
        lThreeCache: 33,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 14,
        partId: 33,
        series: 'Intel Core i7',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 20,
        threadCount: 28,
        performanceCoreClock: 3.4,
        performanceCoreBoostClock: 5.6,
        efficiencyCoreClock: 2.5,
        efficiencyCoreBoostClock: 4.3,
        lTwoCache: 28,
        lThreeCache: 33,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 15,
        partId: 34,
        series: 'Intel Core i5',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 14,
        threadCount: 20,
        performanceCoreClock: 3.5,
        performanceCoreBoostClock: 5.3,
        efficiencyCoreClock: 2.6,
        efficiencyCoreBoostClock: 4.0,
        lTwoCache: 20,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 181,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 16,
        partId: 35,
        series: 'Intel Core i5',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 20,
        threadCount: 28,
        performanceCoreClock: 3.4,
        performanceCoreBoostClock: 5.6,
        efficiencyCoreClock: 2.5,
        efficiencyCoreBoostClock: 4.3,
        lTwoCache: 28,
        lThreeCache: 33,
        tdp: 125,
        maxTurboPower: 181,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 17,
        partId: 36,
        series: 'Intel Core i3',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 4,
        threadCount: 8,
        performanceCoreClock: 3.5,
        performanceCoreBoostClock: 4.7,
        lTwoCache: 5,
        lThreeCache: 12,
        tdp: 58,
        maxTurboPower: 110,
        integrated: 'None',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 18,
        partId: 37,
        series: 'Intel Core i3',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 4,
        threadCount: 8,
        performanceCoreClock: 3.4,
        performanceCoreBoostClock: 4.7,
        lTwoCache: 5,
        lThreeCache: 12,
        tdp: 60,
        maxTurboPower: 110,
        integrated: 'Intel UHD Graphics 730',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 19,
        partId: 38,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 12,
        threadCount: 24,
        performanceCoreClock: 4.4,
        performanceCoreBoostClock: 5.6,
        lTwoCache: 12,
        lThreeCache: 128,
        tdp: 120,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 20,
        partId: 39,
        series: 'AMD Ryzen 9',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 12,
        threadCount: 24,
        performanceCoreClock: 4.7,
        performanceCoreBoostClock: 5.6,
        lTwoCache: 12,
        lThreeCache: 64,
        tdp: 170,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 21,
        partId: 40,
        series: 'AMD Ryzen 7',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 8,
        threadCount: 16,
        performanceCoreClock: 4.2,
        performanceCoreBoostClock: 5.0,
        lTwoCache: 8,
        lThreeCache: 96,
        tdp: 120,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 22,
        partId: 41,
        series: 'AMD Ryzen 7',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 8,
        threadCount: 16,
        performanceCoreClock: 4.5,
        performanceCoreBoostClock: 5.4,
        lTwoCache: 8,
        lThreeCache: 32,
        tdp: 105,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 23,
        partId: 42,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 4.7,
        performanceCoreBoostClock: 5.3,
        lTwoCache: 6,
        lThreeCache: 32,
        tdp: 105,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 24,
        partId: 43,
        series: 'AMD Ryzen 5',
        microarchitecture: 'Zen 4',
        coreFamily: 'Raphael',
        socket: 'AM5',
        coreCount: 6,
        threadCount: 12,
        performanceCoreClock: 3.8,
        performanceCoreBoostClock: 5.1,
        lTwoCache: 6,
        lThreeCache: 32,
        tdp: 65,
        integrated: 'Radeon',
        memoryMax: 128,
        lithography: 5,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 25,
        partId: 44,
        series: 'AMD Ryzen 3',
        microarchitecture: 'Zen 2',
        coreFamily: 'Matisse',
        socket: 'AM4',
        coreCount: 4,
        threadCount: 8,
        performanceCoreClock: 3.8,
        performanceCoreBoostClock: 4.3,
        lTwoCache: 2,
        lThreeCache: 16,
        tdp: 65,
        integrated: 'None',
        memoryMax: 128,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 26,
        partId: 45,
        series: 'AMD Ryzen 3',
        microarchitecture: 'Zen+',
        coreFamily: 'Picasso',
        socket: 'AM4',
        coreCount: 4,
        threadCount: 4,
        performanceCoreClock: 3.6,
        performanceCoreBoostClock: 4.0,
        lTwoCache: 2,
        lThreeCache: 4,
        tdp: 65,
        integrated: 'Radeon Vega 8',
        memoryMax: 64,
        lithography: 12,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 27,
        partId: 46,
        series: 'AMD Ryzen 3',
        microarchitecture: 'Zen 2',
        coreFamily: 'Matisse',
        socket: 'AM4',
        coreCount: 4,
        threadCount: 8,
        performanceCoreClock: 3.6,
        performanceCoreBoostClock: 3.9,
        lTwoCache: 2,
        lThreeCache: 16,
        tdp: 65,
        integrated: 'None',
        memoryMax: 128,
        lithography: 7,
        includedCooler: 1,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 28,
        partId: 47,
        series: 'Intel Core i9',
        microarchitecture: 'Alder Lake',
        coreFamily: 'Alder Lake',
        socket: 'LGA1700',
        coreCount: 16,
        threadCount: 24,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 3.9,
        lTwoCache: 14,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 241,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 128,
        lithography: 10,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 29,
        partId: 48,
        series: 'Intel Core i9',
        microarchitecture: 'Alder Lake',
        coreFamily: 'Alder Lake',
        socket: 'LGA1700',
        coreCount: 16,
        threadCount: 24,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 5.2,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 3.9,
        lTwoCache: 14,
        lThreeCache: 30,
        tdp: 125,
        maxTurboPower: 241,
        integrated: 'None',
        memoryMax: 128,
        lithography: 10,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 30,
        partId: 49,
        series: 'Intel Core i5',
        microarchitecture: 'Raptor Lake',
        coreFamily: 'Raptor Lake',
        socket: 'LGA1700',
        coreCount: 14,
        threadCount: 20,
        performanceCoreClock: 3.5,
        performanceCoreBoostClock: 5.1,
        efficiencyCoreClock: 2.6,
        efficiencyCoreBoostClock: 3.9,
        lTwoCache: 20,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 181,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 10,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cpuId: 31,
        partId: 50,
        series: 'Intel Core i5',
        microarchitecture: 'Raptor Lake',
        coreFamily: 'Raptor Lake',
        socket: 'LGA1700',
        coreCount: 14,
        threadCount: 20,
        performanceCoreClock: 3.5,
        performanceCoreBoostClock: 5.1,
        efficiencyCoreClock: 2.6,
        efficiencyCoreBoostClock: 3.9,
        lTwoCache: 20,
        lThreeCache: 24,
        tdp: 125,
        maxTurboPower: 181,
        integrated: 'None',
        memoryMax: 192,
        lithography: 10,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Cpu', null, {}); // Delete all Cpu records
  }
};

/*
      {
        cpuId: 11,
        partId: 11,
        series: 'Intel Core i9',
        microarchitecture: 'Raptor Lake Refresh',
        coreFamily: 'Raptor Lake Refresh',
        socket: 'LGA1700',
        coreCount: 24,
        threadCount: 32,
        performanceCoreClock: 3.2,
        performanceCoreBoostClock: 6.0,
        efficiencyCoreClock: 2.4,
        efficiencyCoreBoostClock: 4.4,
        lTwoCache: 36,
        lThreeCache: 36,
        tdp: 125,
        maxTurboPower: 253,
        integrated: 'Intel UHD Graphics 770',
        memoryMax: 192,
        lithography: 7,
        includedCooler: 0,
        multithreading: 1, // tinyint(1) for true
        createdAt: new Date(),
        updatedAt: new Date(),
      },
*/
