'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Memory', [
      {
        memoryId: 1,
        partId: 16,
        memoryType: 'DDR4',
        speed: 3000,
        casLatency: 15,
        trueLatency: 10,
        capacity: 16,
        modules: 2, // 2 x 8 GB
        pricePerGig: 2.499,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Yellow',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 2,
        partId: 17,
        memoryType: 'DDR5',
        speed: 5600,
        casLatency: 36,
        trueLatency: 12.857,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 3.437,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.25,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 3,
        partId: 18,
        memoryType: 'DDR5',
        speed: 6400,
        casLatency: 32,
        trueLatency: 10,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 4.312,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'White / Silver',
        voltage: 1.4,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 4,
        partId: 65,
        memoryType: 'DDR4',
        speed: 2400,
        casLatency: 16,
        trueLatency: 13.333,
        capacity: 8,
        modules: 1, // 1 x 8 GB
        pricePerGig: 2.248,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Yellow',
        voltage: 1.2,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 5,
        partId: 66,
        memoryType: 'DDR4',
        speed: 2400,
        casLatency: 16,
        trueLatency: 13.333,
        capacity: 8,
        modules: 1, // 1 x 8 GB
        pricePerGig: 19.875,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Silver',
        voltage: 1.2,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 6,
        partId: 67,
        memoryType: 'DDR4',
        speed: 2133,
        casLatency: 15,
        trueLatency: 14.065,
        capacity: 8,
        modules: 1, // 1 x 8 GB
        pricePerGig: 2.375,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Green',
        voltage: 1.2,
        heatSpreader: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 7,
        partId: 68,
        memoryType: 'DDR4',
        speed: 3000,
        casLatency: 15,
        trueLatency: 10.667,
        capacity: 8,
        modules: 1, // 1 x 8 GB
        pricePerGig: 2.516,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Red',
        voltage: 1.35,
        heatSpreader: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 8,
        partId: 69,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 8,
        modules: 1, // 1 x 8 GB
        pricePerGig: 2.694,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 9,
        partId: 70,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 16,
        modules: 2, // 2 x 8 GB
        pricePerGig: 2.874,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 10,
        partId: 71,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 16,
        modules: 2, // 2 x 8 GB
        pricePerGig: 2.562,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'White',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 11,
        partId: 72,
        memoryType: 'DDR4',
        speed: 3600,
        casLatency: 16,
        trueLatency: 8.889,
        capacity: 16,
        modules: 2, // 2 x 8 GB
        pricePerGig: 2.249,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 12,
        partId: 73,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 16,
        modules: 1, // 1 x 16 GB
        pricePerGig: 1.749,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 13,
        partId: 74,
        memoryType: 'DDR4',
        speed: 2400,
        casLatency: 15,
        trueLatency: 12.500,
        capacity: 16,
        modules: 1, // 1 x 16 GB
        pricePerGig: 4.062,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.2,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 14,
        partId: 75,
        memoryType: 'DDR4',
        speed: 3600,
        casLatency: 16,
        trueLatency: 8.889,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 2.437,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Silver',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 15,
        partId: 76,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 1.437,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 16,
        partId: 77,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 1.906,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 17,
        partId: 78,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 32,
        modules: 1, // 1 x 16 GB
        pricePerGig: 1.875,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 18,
        partId: 79,
        memoryType: 'DDR4',
        speed: 3600,
        casLatency: 20,
        trueLatency: 11.111,
        capacity: 32,
        modules: 1, // 1 x 16 GB
        pricePerGig: 1.718,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 19,
        partId: 80,
        memoryType: 'DDR4',
        speed: 3200,
        casLatency: 16,
        trueLatency: 10.000,
        capacity: 64,
        modules: 2, // 2 x 32 GB
        pricePerGig: 3.250,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 20,
        partId: 81,
        memoryType: 'DDR4',
        speed: 3600,
        casLatency: 16,
        trueLatency: 8.889,
        capacity: 64,
        modules: 2, // 2 x 32 GB
        pricePerGig: 1.968,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 21,
        partId: 82,
        memoryType: 'DDR4',
        speed: 3600,
        casLatency: 18,
        trueLatency: 10.000,
        capacity: 64,
        modules: 2, // 2 x 32 GB
        pricePerGig: 2.000,
        formFactor: '288-pin DIMM (DDR4)',
        color: 'Black / Yellow',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 22,
        partId: 83,
        memoryType: 'DDR5',
        speed: 6000,
        casLatency: 30,
        trueLatency: 10.000,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 3.343,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 23,
        partId: 84,
        memoryType: 'DDR5',
        speed: 6000,
        casLatency: 32,
        trueLatency: 10.667,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 2.594,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 24,
        partId: 85,
        memoryType: 'DDR5',
        speed: 6000,
        casLatency: 30,
        trueLatency: 10.000,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 3.218,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 25,
        partId: 86,
        memoryType: 'DDR5',
        speed: 6000,
        casLatency: 30,
        trueLatency: 10.000,
        capacity: 32,
        modules: 2, // 2 x 16 GB
        pricePerGig: 2.687,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'White',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 26,
        partId: 87,
        memoryType: 'DDR5',
        speed: 5600,
        casLatency: 38,
        trueLatency: 13.571,
        capacity: 32,
        modules: 1, // 1 x 32 GB
        pricePerGig: 2.593,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'White',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 27,
        partId: 88,
        memoryType: 'DDR5',
        speed: 6400,
        casLatency: 32,
        trueLatency: 10.000,
        capacity: 64,
        modules: 2, // 2 x 32 GB
        pricePerGig: 3.265,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black / Silver',
        voltage: 1.35,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 29,
        partId: 89,
        memoryType: 'DDR5',
        speed: 6000,
        casLatency: 30,
        trueLatency: 10.000,
        capacity: 64,
        modules: 2, // 2 x 32 GB
        pricePerGig: 2.812,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.4,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        memoryId: 30,
        partId: 90,
        memoryType: 'DDR5',
        speed: 6400,
        casLatency: 32,
        trueLatency: 10.000,
        capacity: 92,
        modules: 2, // 2 x 48 GB
        pricePerGig: 3.542,
        formFactor: '288-pin DIMM (DDR5)',
        color: 'Black',
        voltage: 1.4,
        heatSpreader: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Memory', null, {});
  }
};
